### ISSUE TITLE
setup-pre-510.sh broken in 5.6.0

### ISSUE THREAD

**Issue by adamtulinius** [pongasoft/glu#296]
Same thing happens with both java 7 and java 8. The script from 5.5.6 works fine.

Here's the output when running on java 8:

```
$ ./bin/setup-pre-510.sh
### Setting up pre 5.1.0 distributions...
Exception in thread "main" java.lang.VerifyError: Bad <init> method call from inside of a branch
Exception Details:
  Location:
    org/linkedin/groovy/util/ant/AntBuilder6068.<init>()V @87: invokespecial
  Reason:
    Error exists in the bytecode
  Bytecode:
    0x0000000: b800 1f4c b800 259a 0006 a700 ac04 bd00
    0x0000010: 2759 032b 1228 3212 02b9 002e 0200 5359
    0x0000020: 10ff 1202 b800 342a 5fab 0000 0000 007f
    0x0000030: 0000 0004 0000 9b75 0000 002b 0239 44dd
    0x0000040: 0000 0034 29cb 09a1 0000 0049 4626 9615
    0x0000050: 0000 006a 5f5a 57b7 0036 a700 585f 5a59
    0x0000060: 0332 1238 b800 3cc0 0038 5f57 b700 3fa7
    0x0000070: 0043 5f5a 5903 3212 38b8 003c c000 385f
    0x0000080: 5904 3212 41b8 003c c000 415f 57b7 0044
    0x0000090: a700 225f 5a59 0332 1246 b800 3cc0 0046
    0x00000a0: 5f57 b700 49a7 000d bb00 4b59 124d b700
    0x00000b0: 50bf 57a7 00a0 04bd 0027 5903 b800 5453
    0x00000c0: 5910 ff12 02b8 0034 2a5f ab00 0000 007e
    0x00000d0: 0000 0004 0000 9b75 0000 002a 0239 44dd
    0x00000e0: 0000 0033 29cb 09a1 0000 0048 4626 9615
    0x00000f0: 0000 0069 5f5a 57b7 0036 a700 585f 5a59
    0x0000100: 0332 1238 b800 3cc0 0038 5f57 b700 3fa7
    0x0000110: 0043 5f5a 5903 3212 38b8 003c c000 385f
    0x0000120: 5904 3212 41b8 003c c000 415f 57b7 0044
    0x0000130: a700 225f 5a59 0332 1246 b800 3cc0 0046
    0x0000140: 5f57 b700 49a7 000d bb00 4b59 124d b700
    0x0000150: 50bf 57b1
  Stackmap Table:
    append_frame(@13,Object[#88])
    full_frame(@84,{UninitializedThis,Object[#88]},{Object[#90],UninitializedThis})
    full_frame(@93,{UninitializedThis,Object[#88]},{Object[#90],UninitializedThis})
    full_frame(@114,{UninitializedThis,Object[#88]},{Object[#90],UninitializedThis})
    full_frame(@147,{UninitializedThis,Object[#88]},{Object[#90],UninitializedThis})
    full_frame(@168,{UninitializedThis,Object[#88]},{Object[#90],UninitializedThis})
    full_frame(@178,{Object[#2],Object[#88]},{Object[#90]})
    full_frame(@182,{UninitializedThis,Object[#88]},{})
    full_frame(@244,{UninitializedThis,Object[#88]},{Object[#90],UninitializedThis})
    full_frame(@253,{UninitializedThis,Object[#88]},{Object[#90],UninitializedThis})
    full_frame(@274,{UninitializedThis,Object[#88]},{Object[#90],UninitializedThis})
    full_frame(@307,{UninitializedThis,Object[#88]},{Object[#90],UninitializedThis})
    full_frame(@328,{UninitializedThis,Object[#88]},{Object[#90],UninitializedThis})
    full_frame(@338,{Object[#2],Object[#88]},{Object[#90]})
    same_frame(@339)

	at java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.lang.Class.privateGetDeclaredConstructors(Class.java:2658)
	at java.lang.Class.getDeclaredConstructors(Class.java:2007)
	at org.codehaus.groovy.reflection.CachedClass$2$1.run(CachedClass.java:71)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.codehaus.groovy.reflection.CachedClass$2.initValue(CachedClass.java:68)
	at org.codehaus.groovy.reflection.CachedClass$2.initValue(CachedClass.java:66)
	at org.codehaus.groovy.util.LazyReference.getLocked(LazyReference.java:46)
	at org.codehaus.groovy.util.LazyReference.get(LazyReference.java:33)
	at org.codehaus.groovy.reflection.CachedClass.getConstructors(CachedClass.java:265)
	at groovy.lang.MetaClassImpl.<init>(MetaClassImpl.java:215)
	at groovy.lang.MetaClassImpl.<init>(MetaClassImpl.java:225)
	at groovy.lang.MetaClassRegistry$MetaClassCreationHandle.createNormalMetaClass(MetaClassRegistry.java:168)
	at groovy.lang.MetaClassRegistry$MetaClassCreationHandle.createWithCustomLookup(MetaClassRegistry.java:158)
	at groovy.lang.MetaClassRegistry$MetaClassCreationHandle.create(MetaClassRegistry.java:141)
	at org.codehaus.groovy.reflection.ClassInfo.getMetaClassUnderLock(ClassInfo.java:250)
	at org.codehaus.groovy.reflection.ClassInfo.getMetaClass(ClassInfo.java:282)
	at org.codehaus.groovy.runtime.metaclass.MetaClassRegistryImpl.getMetaClass(MetaClassRegistryImpl.java:255)
	at org.codehaus.groovy.runtime.InvokerHelper.getMetaClass(InvokerHelper.java:872)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.createCallConstructorSite(CallSiteArray.java:84)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallConstructor(CallSiteArray.java:57)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:232)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:236)
	at org.linkedin.groovy.util.ant.AntUtils.withBuilder(AntUtils.groovy:38)
	at org.linkedin.groovy.util.ant.AntUtils$withBuilder$0.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:110)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:122)
	at org.linkedin.groovy.util.ant.AntUtils.tempFile(AntUtils.groovy:94)
	at org.linkedin.groovy.util.ant.AntUtils$tempFile.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:110)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:122)
	at org.linkedin.groovy.util.io.fs.FileSystemImpl.<init>(FileSystemImpl.groovy:41)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:408)
	at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:77)
	at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrapNoCoerce.callConstructor(ConstructorSite.java:102)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallConstructor(CallSiteArray.java:57)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:232)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:244)
	at org.linkedin.glu.groovy.utils.shell.ShellImpl.createRootShell(ShellImpl.groovy:100)
	at org.linkedin.glu.groovy.utils.shell.ShellImpl$createRootShell.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:110)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:114)
	at org.pongasoft.glu.packaging.setup.SetupMain.<init>(SetupMain.groovy:80)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:408)
	at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:77)
	at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrapNoCoerce.callConstructor(ConstructorSite.java:102)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallConstructor(CallSiteArray.java:57)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:232)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:236)
	at org.pongasoft.glu.packaging.setup.SetupMain.main(SetupMain.groovy:476)
### Creating agent upgrade...
./bin/setup-pre-510.sh: line 80: cd: /home/atu/glu/org.linkedin.glu.packaging-all-5.6.0/pre-510/dists/agents/org.linkedin.glu.agent-server-upgrade-5.6.0: No such file or directory
tar (child): /home/atu/glu/org.linkedin.glu.packaging-all-5.6.0/pre-510/org.linkedin.glu.agent-server-upgrade-5.6.0.tgz: Cannot open: No such file or directory
tar (child): Error is not recoverable: exiting now
### Creating console war...
./bin/setup-pre-510.sh: line 85: cd: /home/atu/glu/org.linkedin.glu.packaging-all-5.6.0/pre-510/dists/consoles/org.linkedin.glu.console-server-5.6.0/glu/repository/exploded-wars/org.linkedin.glu.console-webapp-5.6.0: No such file or directory
java.io.FileNotFoundException: META-INF/MANIFEST.MF (No such file or directory)
	at java.io.FileInputStream.open(Native Method)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at java.io.FileInputStream.<init>(FileInputStream.java:93)
	at sun.tools.jar.Main.run(Main.java:173)
	at sun.tools.jar.Main.main(Main.java:1233)
### Moving files around...
mv: cannot stat `/home/atu/glu/org.linkedin.glu.packaging-all-5.6.0/pre-510/dists/agents/org.linkedin.glu.agent-server-5.6.0': No such file or directory
mv: cannot stat `/home/atu/glu/org.linkedin.glu.packaging-all-5.6.0/pre-510/dists/agent-cli/org.linkedin.glu.agent-cli-5.6.0': No such file or directory
mv: cannot stat `/home/atu/glu/org.linkedin.glu.packaging-all-5.6.0/pre-510/dists/consoles/org.linkedin.glu.console-server-5.6.0': No such file or directory
mv: cannot stat `/home/atu/glu/org.linkedin.glu.packaging-all-5.6.0/pre-510/dists/console-cli/org.linkedin.glu.console-cli-5.6.0': No such file or directory
mv: cannot stat `/home/atu/glu/org.linkedin.glu.packaging-all-5.6.0/pre-510/dists/zookeeper-clusters/zookeeper-cluster/org.linkedin.zookeeper-server-2.1.0': No such file or directory
### Creating shortcuts...
mkdir: cannot create directory `/home/atu/glu/org.linkedin.glu.packaging-all-5.6.0/pre-510/bin': No such file or directory
ln: failed to create symbolic link `/home/atu/glu/org.linkedin.glu.packaging-all-5.6.0/pre-510/bin/agent-server.sh': No such file or directory
ln: failed to create symbolic link `/home/atu/glu/org.linkedin.glu.packaging-all-5.6.0/pre-510/bin/agent-cli.sh': No such file or directory
ln: failed to create symbolic link `/home/atu/glu/org.linkedin.glu.packaging-all-5.6.0/pre-510/bin/console-server.sh': No such file or directory
ln: failed to create symbolic link `/home/atu/glu/org.linkedin.glu.packaging-all-5.6.0/pre-510/bin/console-cli.sh': No such file or directory
ln: failed to create symbolic link `/home/atu/glu/org.linkedin.glu.packaging-all-5.6.0/pre-510/bin/zookeeper-server.sh': No such file or directory
### Cleanup...
### Setup complete.
```

**Comment by ypujante** [comment]
I will investigate. It seems that this thread is showing a similar issue: https://github.com/renatoathaydes/Automaton/issues/23 not sure if it can help or not. 

Will get back to you shortly

**Comment by ypujante** [comment]
I cannot reproduce. Here is my output (with java 7 and java 8).

```
> java -version
java version "1.7.0_79"
Java(TM) SE Runtime Environment (build 1.7.0_79-b15)
Java HotSpot(TM) 64-Bit Server VM (build 24.79-b02, mixed mode)

> ./bin/setup-pre-510.sh
### Setting up pre 5.1.0 distributions...
2015/05/14 08:55:50.401 INFO [SetupMain] Generating distributions
2015/05/14 08:55:53.641 INFO [GluPackager] Generated agent package file:/Volumes/Vault/deployment/content/glu/org.linkedin.glu.packaging-all-5.6.0/pre-510/dists/agents/org.linkedin.glu.agent-server-5.6.0/ => localhost:12906
2015/05/14 08:56:01.280 INFO [GluPackager] Generated console package file:/Volumes/Vault/deployment/content/glu/org.linkedin.glu.packaging-all-5.6.0/pre-510/dists/consoles/org.linkedin.glu.console-server-5.6.0/ => localhost:8080
2015/05/14 08:56:02.049 INFO [GluPackager] Generated ZooKeeper instance [1] file:/Volumes/Vault/deployment/content/glu/org.linkedin.glu.packaging-all-5.6.0/pre-510/dists/zookeeper-clusters/zookeeper-cluster/org.linkedin.zookeeper-server-2.1.0/ => 127.0.0.1:2181
2015/05/14 08:56:02.050 INFO [GluPackager] Generated ZooKeeper cluster [default] file:/Volumes/Vault/deployment/content/glu/org.linkedin.glu.packaging-all-5.6.0/pre-510/dists/zookeeper-clusters/zookeeper-cluster/
2015/05/14 08:56:02.689 INFO [GluPackager] Generated agent cli package file:/Volumes/Vault/deployment/content/glu/org.linkedin.glu.packaging-all-5.6.0/pre-510/dists/agent-cli/org.linkedin.glu.agent-cli-5.6.0/
2015/05/14 08:56:02.774 INFO [GluPackager] Generated console cli package file:/Volumes/Vault/deployment/content/glu/org.linkedin.glu.packaging-all-5.6.0/pre-510/dists/console-cli/org.linkedin.glu.console-cli-5.6.0/
2015/05/14 08:56:02.858 INFO [GluPackager] Generated install script file:/Volumes/Vault/deployment/content/glu/org.linkedin.glu.packaging-all-5.6.0/pre-510/dists/bin/install-zookeepers.sh
2015/05/14 08:56:02.891 INFO [GluPackager] Generated install script file:/Volumes/Vault/deployment/content/glu/org.linkedin.glu.packaging-all-5.6.0/pre-510/dists/bin/install-agents.sh
2015/05/14 08:56:02.926 INFO [GluPackager] Generated install script file:/Volumes/Vault/deployment/content/glu/org.linkedin.glu.packaging-all-5.6.0/pre-510/dists/bin/install-consoles.sh
2015/05/14 08:56:02.964 INFO [GluPackager] Generated install script file:/Volumes/Vault/deployment/content/glu/org.linkedin.glu.packaging-all-5.6.0/pre-510/dists/bin/install-agent-cli.sh
2015/05/14 08:56:02.995 INFO [GluPackager] Generated install script file:/Volumes/Vault/deployment/content/glu/org.linkedin.glu.packaging-all-5.6.0/pre-510/dists/bin/install-console-cli.sh
2015/05/14 08:56:03.027 INFO [GluPackager] Generated install script file:/Volumes/Vault/deployment/content/glu/org.linkedin.glu.packaging-all-5.6.0/pre-510/dists/bin/install-all.sh
2015/05/14 08:56:03.027 INFO [SetupMain] All distributions generated successfully.
### Creating agent upgrade...
### Creating console war...
### Moving files around...
### Creating shortcuts...
### Cleanup...
### Setup complete.

#####################
> java -version
java version "1.8.0_45"
Java(TM) SE Runtime Environment (build 1.8.0_45-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.45-b02, mixed mode)

> ./bin/setup-pre-510.sh 
### Setting up pre 5.1.0 distributions...
2015/05/14 08:57:41.804 INFO [SetupMain] Generating distributions
2015/05/14 08:57:42.960 INFO [GluPackager] Generated agent package file:/Volumes/Vault/deployment/content/glu/org.linkedin.glu.packaging-all-5.6.0/pre-510/dists/agents/org.linkedin.glu.agent-server-5.6.0/ => localhost:12906
2015/05/14 08:57:45.169 INFO [GluPackager] Generated console package file:/Volumes/Vault/deployment/content/glu/org.linkedin.glu.packaging-all-5.6.0/pre-510/dists/consoles/org.linkedin.glu.console-server-5.6.0/ => localhost:8080
2015/05/14 08:57:45.473 INFO [GluPackager] Generated ZooKeeper instance [1] file:/Volumes/Vault/deployment/content/glu/org.linkedin.glu.packaging-all-5.6.0/pre-510/dists/zookeeper-clusters/zookeeper-cluster/org.linkedin.zookeeper-server-2.1.0/ => 127.0.0.1:2181
2015/05/14 08:57:45.474 INFO [GluPackager] Generated ZooKeeper cluster [default] file:/Volumes/Vault/deployment/content/glu/org.linkedin.glu.packaging-all-5.6.0/pre-510/dists/zookeeper-clusters/zookeeper-cluster/
2015/05/14 08:57:45.800 INFO [GluPackager] Generated agent cli package file:/Volumes/Vault/deployment/content/glu/org.linkedin.glu.packaging-all-5.6.0/pre-510/dists/agent-cli/org.linkedin.glu.agent-cli-5.6.0/
2015/05/14 08:57:45.810 INFO [GluPackager] Generated console cli package file:/Volumes/Vault/deployment/content/glu/org.linkedin.glu.packaging-all-5.6.0/pre-510/dists/console-cli/org.linkedin.glu.console-cli-5.6.0/
2015/05/14 08:57:45.845 INFO [GluPackager] Generated install script file:/Volumes/Vault/deployment/content/glu/org.linkedin.glu.packaging-all-5.6.0/pre-510/dists/bin/install-zookeepers.sh
2015/05/14 08:57:45.872 INFO [GluPackager] Generated install script file:/Volumes/Vault/deployment/content/glu/org.linkedin.glu.packaging-all-5.6.0/pre-510/dists/bin/install-agents.sh
2015/05/14 08:57:45.903 INFO [GluPackager] Generated install script file:/Volumes/Vault/deployment/content/glu/org.linkedin.glu.packaging-all-5.6.0/pre-510/dists/bin/install-consoles.sh
2015/05/14 08:57:45.930 INFO [GluPackager] Generated install script file:/Volumes/Vault/deployment/content/glu/org.linkedin.glu.packaging-all-5.6.0/pre-510/dists/bin/install-agent-cli.sh
2015/05/14 08:57:45.960 INFO [GluPackager] Generated install script file:/Volumes/Vault/deployment/content/glu/org.linkedin.glu.packaging-all-5.6.0/pre-510/dists/bin/install-console-cli.sh
2015/05/14 08:57:45.981 INFO [GluPackager] Generated install script file:/Volumes/Vault/deployment/content/glu/org.linkedin.glu.packaging-all-5.6.0/pre-510/dists/bin/install-all.sh
2015/05/14 08:57:45.981 INFO [SetupMain] All distributions generated successfully.
### Creating agent upgrade...
### Creating console war...
### Moving files around...
### Creating shortcuts...
### Cleanup...
### Setup complete.
```

**Comment by adamtulinius** [comment]
Thanks for looking into the issue. I think you're right, we're still on Java 8u20 (and Java 7u67) so I think the problem will go away after we roll out new Java packages.

Sorry for wasting your time. :-(

**Comment by ypujante** [comment]
No Problem. I do realize I had not tested this script prior to releasing. It's good to know that the issue is with the version of java not glu :)
